PersonInfo/PersonInfo/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from PersonInfoSite import views
from UserSite import views
# from eventhandler import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^users/', include('PersonInfoSite.urls')),
    url(r'^usersite/', include('UserSite.urls')),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'^special/$',views.special, name='special'),
    url(r'^events/', include('eventhandler.urls'))
]

PersonInfo/PersonInfoSite/urls.py
from django.conf.urls import url
from PersonInfoSite import views

app_name = 'PersonInfo'

urlpatterns = [
    url(r'^$', views.person, name='persons'),
    url(r'^/addperson/',views.addperson,name='addperson')
]

PersonInfo/UserSite/urls.py
from django.conf.urls import url,include
from UserSite import views

app_name = 'basic_app'

urlpatterns = [
    url(r'^register/$', views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
]

PersonInfo/eventhandler/urls.py
from django.conf.urls import url
from eventhandler import views

app_name = 'eventhandler'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^addevent/$', views.addevent, name='addevent'),
    url(r'^picrandomevent$', views.event, name='PicRandomEvent')
]

PersonInfo/PersonInfoSite/models.py
from django.db import models

# Create your models here.
class Person(models.Model):
    '''asdfasdf'''
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.CharField(max_length=150,unique=True)
    height = models.IntegerField(max_length=200,unique=True)
    age = models.IntegerField(max_length=200,default=10)

PersonInfo/UserSite/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User)

    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username


# Create your models here.

PersonInfo/eventhandler/models.py
from django.db import models

# Create your models here.
class Event(models.Model):
    '''event model class'''
    event_text = models.TextField(max_length=600)

PersonInfo/PersonInfoSite/forms.py
from django import forms
from PersonInfoSite.models import Person

class NewPerson(forms.ModelForm):
    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.CharField()
    height = forms.IntegerField(max_value=200)
    age = forms.IntegerField(max_value=100)

    class Meta:
        model = Person
        fields = '__all__'

PersonInfo/UserSite/forms.py
from django import forms
from django.contrib.auth.models import User
from UserSite.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

PersonInfo/eventhandler/forms.py
from django import forms
from eventhandler.models import Event

class NewEvent(forms.ModelForm):
    event_text = forms.TextInput()

    class Meta:
        model = Event
        fields = '__all__'

PersonInfo/PersonInfoSite/views.py
from django.shortcuts import render
from PersonInfoSite.models import Person
from . import forms
from django.contrib.auth.decorators import login_required
# Create your views here.
@login_required
def person(request):
    persons = Person.objects.order_by('first_name')
    person_dic = {'persons':persons}
    return render(request,'PersonInfoSite/persons.html',context=person_dic)

def index(request):
    return render(request,'PersonInfoSite/HTML.html')

@login_required
def addperson(request):
    form = forms.NewPerson()

    if request.method == 'POST':
        form = forms.NewPerson(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return person(request)

        else:
            print('ERROR FORM INVALID')

    return render(request,'PersonInfoSite/AddPerson.html',{'form':form})

PersonInfo/UserSite/views.py
from django.shortcuts import render
from UserSite.forms import UserProfileInfoForm,UserForm
from PersonInfoSite.models import Person

from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect,  HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    return render(request, 'UserSite/index.html')

def register(request):

    registered = False

    if request.method == 'POST':

        # Get info from "both" forms
        # It appears as one form to the user on the .html page
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        # Check to see both forms are valid
        if user_form.is_valid() and profile_form.is_valid():

            # Save User Form to Database
            user = user_form.save()

            # Hash the password
            user.set_password(user.password)

            # Update with Hashed password
            user.save()

            # Now we deal with the extra info!

            # Can't commit yet because we still need to manipulate
            profile = profile_form.save(commit=False)

            # Set One to One relationship between
            # UserForm and UserProfileInfoForm
            profile.user = user

            # Check if they provided a profile picture
            if 'profile_pic' in request.FILES:
                print('found it')
                # If yes, then grab it from the POST form reply
                profile.profile_pic = request.FILES['profile_pic']

            # Now save model
            profile.save()

            # Registration Successful!
            registered = True

        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors,profile_form.errors)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    return render(request,'UserSite/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})


@login_required
def special(request):
    persons = Person.objects.order_by('first_name')
    person_dic = {'persons':persons}
    return render(request,'PersonInfoSite/persons.html',context=person_dic)

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")

        else:
            print('Someone tried to login and failed!')
            print('Username: {} and password {}'.format(username, password))

            return HttpResponse('invalid login details supplied!')

    else:
        return render(request,'UserSite/login.html',{})

PersonInfo/eventhandler/views.py
from django.shortcuts import render
from eventhandler.models import Event
from . import forms
from django.contrib.auth.decorators import login_required


@login_required
def event(request):
    event = Event.objects.order_by('event_text')
    event_dic = {'event':event}
    return render(request,'eventhandler/PicRandomEvent.html',context=event_dic)

def index(request):
    return render(request, 'eventhandler/MainEventSite.html',{})

@login_required
def addevent(request):
    form = forms.NewEvent()

    if request.method == 'POST':
        form = forms.NewEvent(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return event(request)

        else:
            print('ERROR FORM INVALID')

    return render(request,'eventhandler/AddEvent.html',{'form':form})

PersonInfo/templates/PersonInfoSite/AddPerson.html
<!DOCTYPE html>
{% extends "PersonInfoSite/basic.html" %}
{% block body_block %}

    <h2>Add person Info:</h2>

    <div class="container">

      <form method="POST" class="form-inline">
        <div class="form-group">
          {{ form.as_p }}
          {% csrf_token %}
        </div>
        <input type="submit" class='btn btn-primary' value="Submit">
      </form>

    </div>
{% endblock %}

PersonInfo/templates/PersonInfoSite/HTML.html
<!DOCTYPE html>
{% extends "PersonInfoSite/basic.html" %}
{% block body_block %}
<h1>Home page</h1>
<div class="container">
  <div class="jumbotron">
    <h2>Sites</h2>
    <a class="btn btn-default" href="http://naver.com">Go to naver</a>
    <a class="btn btn-default" href="http://google.com">Go to google</a>
  </div>
</div>
{% endblock %}

PersonInfo/templates/PersonInfoSite/basic.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <title></title>
  </head>
  <body>

    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">

        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">HomePage</a></li>
          <li><a class="navbar-brand" href="{% url 'PersonInfo:persons' %}">Persons</a></li>
          <li><a class="navbar-brand" href="{% url 'PersonInfo:addperson' %}">Add Person</a></li>
          <li><a class="navbar-brand" href="http://127.0.0.1:8000/usersite/register/">Register</a></li>
          <li><a class="navbar-brand" href="{% url 'admin:index' %}">Admin</a></li>
        </ul>

      </div>
    </nav>

    <div class="container">

      {% block body_block %}
      {% endblock %}

    </div>

  </body>
</html>

PersonInfo/templates/PersonInfoSite/persons.html
<!DOCTYPE html>
{% extends "PersonInfoSite/basic.html" %}
{% block body_block %}

    <h1>Here are your persons:</h1>
    {% if persons %}

    <ol>
      {% for person in persons %}
        <div class="jumbotron">
          <li><h2>{{ person.first_name }} {{ person.last_name }} Info</h2></li>
            <ul>
              <li><h5>First Name: {{ person.first_name }}</h5></li>
              <li><h5>Last Name: {{ person.last_name }}</h5></li>
              <li><h5>Email: {{ person.email }}</h5></li>
              <li><h5>Height: {{ person.height }}</h5></li>
              <li><h5>Picture:</h5>{{ person.person_pic }}</li>
            </ul>
        </div>
          {% endfor %}
    </ol>

    {% endif %}

    {% endblock %}

PersonInfo/templates/UserSite/basic.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <title></title>
  </head>
  <body>

    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">

        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">HomePage</a></li>
          <li><a class="navbar-brand" href="http://127.0.0.1:8000/usersite/register/">Register</a></li>


          {% if user.is_authenticated %}

              <li><a class="navbar-brand" href="{% url 'PersonInfo:addperson' %}">Add Person</a></li>
              <li><a class="navbar-brand" href="{% url 'PersonInfo:persons' %}">Persons</a></li>
              <li><a class='navbar-brand' href="{% url 'logout' %}">Logout</a></li>
              <li><a class="navbar-brand" href="{% url 'admin:index' %}">Admin</a></li>

            {% else %}
              <li><a class="navbar-brand" href="http://127.0.0.1:8000/usersite/user_login">Login</a></li>

            {% endif %}

        </ul>

      </div>
    </nav>

    <div class="container">

      {% block body_block %}
      {% endblock %}

    </div>

  </body>
</html>

PersonInfo/templates/UserSite/index.html
<!DOCTYPE html>
{% extends "UserSite/basic.html" %}
{% block body_block %}
  <div class="jumbotron">
    <h1>Welcom!</h1>
  </div>
{% endblock %}

PersonInfo/templates/UserSite/login.html
{% extends "UserSite/basic.html" %}
{% block body_block %}

<div class="jumbotron">

  <h1>Please Login</h1>
  <form action="{% url 'basic_app:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter Username">

    <label for="password">Password:</label>
    <input type="text" name="password">

    <input type="submit" value="Login">

  </form>

</div>

{% endblock %}

PersonInfo/templates/UserSite/registration.html
<!DOCTYPE html>
{% extends "UserSite/basic.html" %}
{% load staticfiles %}

{% block body_block %}
<div class="jumbotron">
  {% if registered %}

      <h1>Thank you for registering!</h1>
  {% else %}
    <h1>Register Here!</h1>
    <h3>Fill out the form:</h3>
    <form method="post" enctype="multipart/form-data">

      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      <input type="submit" value="Register">

    </form>
  {% endif %}
</div>
{% endblock %}

PersonInfo/templates/eventhandler/AddEvent.html
{% extends "eventhandler/base.html" %}

{% block body_block %}

  <div class="jumbotron">
    <h2>Add Event:</h2>

    <div class="container">

      <form method="post" class="form-inline">
        <div class="form-group">
          {{ form.as_p }}
          {% csrf_token %}
        </div>
        <input type="submit" class='btn btn-primary' value="Submit">
      </form>

    </div>
  </div>

{% endblock %}

PersonInfo/templates/eventhandler/MainEventSite.html
{% extends "eventhandler/base.html" %}

{% block body_block %}

  <div class="jumbotron">
    <h1>Welcom to Event site!</h1>
  </div>

{% endblock %}

PersonInfo/templates/eventhandler/PicRandomEvent.html
{% extends "eventhandler/base.html" %}

{% block body_block %}

  <h1>Here are today's event:</h1>
  {% if events %}

    <h1>{{ event }}</h1>



  {% endif %}


{% endblock %}

PersonInfo/templates/eventhandler/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <title></title>
  </head>
  <body>

    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">

        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">HomePage</a></li>
          {# <li><a class="navbar-brand" href="{% url 'eventhandler:events' %}">Events</a></li>#}
          {# <li><a class="navbar-brand" href="{% url 'eventhandler:addevent' %}">Add Event</a></li>#}
          <li><a class="navbar-brand" href="http://127.0.0.1:8000/usersite/register/">Register</a></li>
          <li><a class="navbar-brand" href="{% url 'admin:index' %}">Admin</a></li>

          {% if user.is_authenticated %}

              <li><a class="navbar-brand" href="{% url 'PersonInfo:addperson' %}">Add Person</a></li>
              <li><a class="navbar-brand" href="{% url 'PersonInfo:persons' %}">Persons</a></li>
              <li><a class='navbar-brand' href="{% url 'logout' %}">Logout</a></li>
              <li><a class="navbar-brand" href="{% url 'admin:index' %}">Admin</a></li>

            {% else %}
              <li><a class="navbar-brand" href="http://127.0.0.1:8000/usersite/user_login">Login</a></li>

            {% endif %}

            
        </ul>

      </div>
    </nav>


    <div class="container">

      {% block body_block %}
      {% endblock %}

    </div>

  </body>
</html>